name: Summarize Commits
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          mode: summarize_commits
          api-key: ${{ secrets.CHATGPT_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
