name: Update Changelog
on:
  pull_request:
    types: [closed]
jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: ./
        with:
          mode: generate_changelog
          api-key: ${{ secrets.CHATGPT_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
